import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

public class MiGenetico extends javax.swing.JFrame {

    /**
     * Creates new form MiGenetico
     */
    private ArrayList<Individuo> poblacion;
    private ArrayList fitness;
    private int n, limPoblacion;
    private double lower[];
    private double upper[];
    
    public MiGenetico() {
        
        this.poblacion = new ArrayList();
        this.fitness = new ArrayList();
        this.lower = new double[2];
        this.lower[0] = 13;
        this.lower[1] = 0;
        this.upper = new double[2];
        this.upper[0] = 100;
        this.upper[0] = 100;
        this.n = 2;
        this.limPoblacion = 10;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        textoArea = new javax.swing.JTextArea();
        generaButton = new javax.swing.JButton();
        clonacionButton = new javax.swing.JButton();
        solucionButton = new javax.swing.JButton();
        poblacionLabel = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        areaSolucion = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        textoArea.setColumns(20);
        textoArea.setRows(5);
        jScrollPane1.setViewportView(textoArea);

        generaButton.setText("Genera");
        generaButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                generaButtonActionPerformed(evt);
            }
        });

        clonacionButton.setText("Clonación");
        clonacionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clonacionButtonActionPerformed(evt);
            }
        });

        solucionButton.setText("Solución");
        solucionButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                solucionButtonActionPerformed(evt);
            }
        });

        poblacionLabel.setText("Población");

        areaSolucion.setColumns(20);
        areaSolucion.setRows(5);
        jScrollPane2.setViewportView(areaSolucion);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(poblacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(solucionButton))
                            .addComponent(generaButton))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 341, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(clonacionButton))
                .addContainerGap(119, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(poblacionLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(54, 54, 54)
                        .addComponent(generaButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(2, 2, 2)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 145, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 92, Short.MAX_VALUE)
                .addComponent(clonacionButton)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(157, 157, 157)
                        .addComponent(solucionButton))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(16, 16, 16))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    private void clonacionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clonacionButtonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clonacionButtonActionPerformed

    private void generaButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_generaButtonActionPerformed
        // TODO add your handling code here:
        for(int i = 0; i < limPoblacion; i++)
             poblacion.add(new Individuo(n, lower, upper));
        for(int i = 0; i < poblacion.size(); i++)
            textoArea.append(poblacion.toString() + "\n");
    }//GEN-LAST:event_generaButtonActionPerformed

    private void solucionButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_solucionButtonActionPerformed
        // TODO add your handling code here:
        
        double x[] = new double[n];
        List auxMin = new ArrayList();
        double l[] = lower, u[] = upper;
        double resClon, resInd, atributo1, atributo2, l1, l2, u1, u2;
        
        for(int i = 0; i < poblacion.size(); i++){
                for(int j = 0; j < n; j++)
                    x[j] = poblacion.get(i).getValorIndividuo()[j];
            fitness.add(solucionFuncion(x));
        }
        for(int i = 0; i < fitness.size(); i++)
            areaSolucion.append(fitness.get(i) + "\n");
        auxMin = fitness;
        Collections.sort(auxMin);
        areaSolucion.append("Mínimo " + auxMin.get(0).toString() + "\n");
        //Clonación
        fitness.clear();
        //Generaciones
        for(int gen = 0; gen < 200; gen++){
            for(int i = 0; i < poblacion.size(); i++){
                Individuo clon = new Individuo(n, l, u);
                for(int j = 0; j < n; j++)
                    x[j] = clon.getValorIndividuo()[j];
                resClon = solucionFuncion(x);
                for(int j = 0; j < n; j++)
                    x[j] = poblacion.get(i).getValorIndividuo()[j];
                resInd = solucionFuncion(x);

                if(resClon < resInd){
                    poblacion.set(i, clon);
                    for(int j = 0; j < n; j++)
                        x[j] = clon.getValorIndividuo()[j];
                    atributo1 = x[0]; //Proceso de mutación
                    atributo2 = x[1];
                    if(x[0] > 14)
                        atributo1--;
                    l1 = atributo1;
                    atributo1 = x[0];
                    if(x[0] < 99)
                        atributo1++;
                    u1 = atributo1;
                    if(atributo2 > 1)
                        atributo2--;
                    l2 = atributo2;
                    atributo2 = x[1];
                    if (atributo2 < 99)
                        atributo2++;
                    u2 = atributo2;
                    l[0] = l1;
                    l[1] = l2;
                    u[0] = u1;
                    u[1] = u2;
                }
            }
            textoArea.append("Población clonada \n");
            for(int i = 0; i < poblacion.size(); i++)
                textoArea.append(poblacion.get(i).toString() + "\n");
            for(int i = 0; i < poblacion.size(); i++){
                for(int j = 0; j < n; j++)
                    x[j] = poblacion.get(i).getValorIndividuo()[j];
                fitness.add(solucionFuncion(x));
            }
            for(int i = 0; i < fitness.size(); i++)
                areaSolucion.append(fitness.get(i) + "\n");
            auxMin = fitness;
            Collections.sort(auxMin);
            areaSolucion.append("Mínimo " + auxMin.get(0).toString() + "\n");
        }
        
    }//GEN-LAST:event_solucionButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MiGenetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MiGenetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MiGenetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MiGenetico.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MiGenetico().setVisible(true);
            }
        });
    }

    public double solucionFuncion(double x[]){
        
        return Math.pow((x[0] - 10), 3) + Math.pow((x[1] - 10), 3); //*(-1);
 
    }
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextArea areaSolucion;
    private javax.swing.JButton clonacionButton;
    private javax.swing.JButton generaButton;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JLabel poblacionLabel;
    private javax.swing.JButton solucionButton;
    private javax.swing.JTextArea textoArea;
    // End of variables declaration//GEN-END:variables
}
